/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.mvc.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pos.mvc.controller.CustomerController;
import pos.mvc.model.CustomerModel;

/**
 *
 * @author Thisura
 */
public class CustomerView extends javax.swing.JFrame {
    
    CustomerController customerController;

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
        customerController = new CustomerController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        ManageCustomerPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        CustDetailsPanel = new javax.swing.JPanel();
        CustIDLabel = new javax.swing.JLabel();
        CustTitleLabel = new javax.swing.JLabel();
        CustDOBLabel = new javax.swing.JLabel();
        CustAddressPanel = new javax.swing.JLabel();
        CustNameLabel = new javax.swing.JLabel();
        CustCityLabel = new javax.swing.JLabel();
        CustzipLabel = new javax.swing.JLabel();
        CustProvienceLabel = new javax.swing.JLabel();
        SaveCustButton = new javax.swing.JButton();
        UpdateCustButton = new javax.swing.JButton();
        DeleteCustButton = new javax.swing.JButton();
        CustSalary = new javax.swing.JLabel();
        CustIdText = new javax.swing.JTextField();
        CustDOBText = new javax.swing.JTextField();
        CustTitleText = new javax.swing.JTextField();
        CustProvienceText = new javax.swing.JTextField();
        CustAddressText = new javax.swing.JTextField();
        CustNameText = new javax.swing.JTextField();
        CustSalaryText = new javax.swing.JTextField();
        CustzipText = new javax.swing.JTextField();
        CustCityText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        tablePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLabel.setText("Manage Customer ");

        CustIDLabel.setText("Customer ID");

        CustTitleLabel.setText("Customer Title");

        CustDOBLabel.setText("Customer DOB");

        CustAddressPanel.setText("Address");

        CustNameLabel.setText("Customer Name");

        CustCityLabel.setText("City");

        CustzipLabel.setText("Postal Code");

        CustProvienceLabel.setText("Provience");

        SaveCustButton.setText("Save Customer");
        SaveCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCustButtonActionPerformed(evt);
            }
        });

        UpdateCustButton.setText("Update Customer");
        UpdateCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCustButtonActionPerformed(evt);
            }
        });

        DeleteCustButton.setText("DELETE Customer");
        DeleteCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCustButtonActionPerformed(evt);
            }
        });

        CustSalary.setText("Salary");

        CustIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustIdTextActionPerformed(evt);
            }
        });

        CustDOBText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustDOBTextActionPerformed(evt);
            }
        });

        CustTitleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustTitleTextActionPerformed(evt);
            }
        });

        CustProvienceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustProvienceTextActionPerformed(evt);
            }
        });

        CustAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustAddressTextActionPerformed(evt);
            }
        });

        CustNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustNameTextActionPerformed(evt);
            }
        });

        CustSalaryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustSalaryTextActionPerformed(evt);
            }
        });

        CustzipText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustzipTextActionPerformed(evt);
            }
        });

        CustCityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustCityTextActionPerformed(evt);
            }
        });

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(customerTable);

        javax.swing.GroupLayout CustDetailsPanelLayout = new javax.swing.GroupLayout(CustDetailsPanel);
        CustDetailsPanel.setLayout(CustDetailsPanelLayout);
        CustDetailsPanelLayout.setHorizontalGroup(
            CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustDetailsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DeleteCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustDetailsPanelLayout.createSequentialGroup()
                        .addComponent(CustAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustAddressText))
                    .addGroup(CustDetailsPanelLayout.createSequentialGroup()
                        .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CustTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustDOBLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustDOBText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustNameText)
                            .addGroup(CustDetailsPanelLayout.createSequentialGroup()
                                .addComponent(CustSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(CustDetailsPanelLayout.createSequentialGroup()
                        .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustDetailsPanelLayout.createSequentialGroup()
                                .addComponent(CustzipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustzipText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustDetailsPanelLayout.createSequentialGroup()
                                .addComponent(CustIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustDetailsPanelLayout.createSequentialGroup()
                                .addComponent(CustCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(CustProvienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustProvienceText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 235, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        CustDetailsPanelLayout.setVerticalGroup(
            CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustDetailsPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustDOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustDOBText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CustCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CustCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CustProvienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CustProvienceText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustzipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustzipText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(CustDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveCustButton)
                    .addComponent(UpdateCustButton)
                    .addComponent(DeleteCustButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ManageCustomerPanelLayout = new javax.swing.GroupLayout(ManageCustomerPanel);
        ManageCustomerPanel.setLayout(ManageCustomerPanelLayout);
        ManageCustomerPanelLayout.setHorizontalGroup(
            ManageCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(CustDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ManageCustomerPanelLayout.setVerticalGroup(
            ManageCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BasePanelLayout = new javax.swing.GroupLayout(BasePanel);
        BasePanel.setLayout(BasePanelLayout);
        BasePanelLayout.setHorizontalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BasePanelLayout.setVerticalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanelLayout.createSequentialGroup()
                .addComponent(ManageCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCustButtonActionPerformed
       saveCustomer();
    }//GEN-LAST:event_SaveCustButtonActionPerformed

    private void UpdateCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCustButtonActionPerformed
       // updateCustomer();
    }//GEN-LAST:event_UpdateCustButtonActionPerformed

    private void DeleteCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCustButtonActionPerformed
       // deleteCustomer();
    }//GEN-LAST:event_DeleteCustButtonActionPerformed

    private void CustIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustIdTextActionPerformed

    private void CustDOBTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustDOBTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustDOBTextActionPerformed

    private void CustTitleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustTitleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustTitleTextActionPerformed

    private void CustProvienceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustProvienceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustProvienceTextActionPerformed

    private void CustAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustAddressTextActionPerformed

    private void CustNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustNameTextActionPerformed

    private void CustSalaryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustSalaryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustSalaryTextActionPerformed

    private void CustzipTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustzipTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustzipTextActionPerformed

    private void CustCityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustCityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustCityTextActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        //searchCustomers();
    }//GEN-LAST:event_customerTableMouseClicked
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    private javax.swing.JLabel CustAddressPanel;
    private javax.swing.JTextField CustAddressText;
    private javax.swing.JLabel CustCityLabel;
    private javax.swing.JTextField CustCityText;
    private javax.swing.JLabel CustDOBLabel;
    private javax.swing.JTextField CustDOBText;
    private javax.swing.JPanel CustDetailsPanel;
    private javax.swing.JLabel CustIDLabel;
    private javax.swing.JTextField CustIdText;
    private javax.swing.JLabel CustNameLabel;
    private javax.swing.JTextField CustNameText;
    private javax.swing.JLabel CustProvienceLabel;
    private javax.swing.JTextField CustProvienceText;
    private javax.swing.JLabel CustSalary;
    private javax.swing.JTextField CustSalaryText;
    private javax.swing.JLabel CustTitleLabel;
    private javax.swing.JTextField CustTitleText;
    private javax.swing.JLabel CustzipLabel;
    private javax.swing.JTextField CustzipText;
    private javax.swing.JButton DeleteCustButton;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel ManageCustomerPanel;
    private javax.swing.JButton SaveCustButton;
    private javax.swing.JButton UpdateCustButton;
    private javax.swing.JTable customerTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables

        private void saveCustomer(){
        CustomerModel customerModel = new CustomerModel(CustIdText.getText(), 
                CustTitleText.getText(), 
                CustNameText.getText(), 
                CustDOBText.getText(), 
                Double.parseDouble(CustSalaryText.getText()), 
                CustAddressText.getText(), 
                CustCityText.getText(), 
                CustProvienceText.getText(), 
                CustzipText.getText());
        
        try {
            String responce = customerController.saveCustomer2CC(customerModel);
            JOptionPane.showMessageDialog(this, responce);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
        
}
